### ISSUE TITLE
Speaker description for "Yuta Koshizawa" contains unparsed ruby template code

### ISSUE THREAD

**Issue by bhargavg** [NatashaTheRobot/trySwiftApp#12]
> Yuta is an iOS developer at Qoncept. He is also developing an iOS app `[articles.each {](articles-each.github.io)` as his side project. His posts about Swift on Qiita, Japanese blogging service specialized for programming, are popular with iOS developers in Japan.

This exists in speakers section of both app and website.

**Comment by koher** [comment]
I sent a PR for the topic in #16.
